In [411]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
from sqlalchemy.types import Integer, String

In [412]:
fifa_csv='../13-ETL-Project/data.csv'
fifa_df=pd.read_csv(fifa_csv)
fifa_df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [413]:
fifa_transformed = fifa_df.rename(columns={"ID": "Player_ID"})
fifa_transformed.head()

,Unnamed: 0,Player_ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [414]:
fifa_cols = ["Player_ID","Name","Age","Nationality","Overall","Potential","Club","Value","Wage","Preferred Foot","International Reputation","Weak Foot","Skill Moves","Work Rate","Body Type","Position","Jersey Number","Height","Weight","LS","ST","RS","LW","LF"]
fifa_transformed= fifa_transformed[fifa_cols].copy()
fifa_transformed.head()

,Player_ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Body Type,Position,Jersey Number,Height,Weight,LS,ST,RS,LW,LF
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,...,Messi,RF,10.0,5'7,159lbs,88+2,88+2,88+2,92+2,93+2
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,C. Ronaldo,ST,7.0,6'2,183lbs,91+3,91+3,91+3,89+3,90+3
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,...,Neymar,LW,10.0,5'9,150lbs,84+3,84+3,84+3,89+3,89+3
3,193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Right,...,Lean,GK,1.0,6'4,168lbs,NaN,NaN,NaN,NaN,NaN
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Right,...,Normal,RCM,7.0,5'11,154lbs,82+3,82+3,82+3,87+3,87+3

In [415]:
player_info_df=fifa_transformed[['Player_ID','Name','Nationality','Club','Age','Weight','Height']]
player_info_df.head()

,Player_ID,Name,Nationality,Club,Age,Weight,Height
0,158023,L. Messi,Argentina,FC Barcelona,31,159lbs,5'7
1,20801,Cristiano Ronaldo,Portugal,Juventus,33,183lbs,6'2
2,190871,Neymar Jr,Brazil,Paris Saint-Germain,26,150lbs,5'9
3,193080,De Gea,Spain,Manchester United,27,168lbs,6'4
4,192985,K. De Bruyne,Belgium,Manchester City,27,154lbs,5'11

In [416]:
fifa2_csv='../13-ETL-Project/Full_DF.csv'
fifa2_df=pd.read_csv(fifa2_csv)
fifa2_df.head()

,Player_ID,ln_value,Name,Value (M),Position,Overall,Potential,pot_grade,ovr_grade,age_grade,...,prefers_lcb,prefers_gk,foot_Left,foot_Right,att_rate_High,att_rate_Low,att_rate_Medium,defend_rate_High,defend_rate_Low,defend_rate_Medium
0,20801,6.862758,Cristiano Ronaldo,95.5,ST,94,94,100.000000,100.000000,48.387097,...,False,0,0,1,1,0,0,0,1,0
1,158023,6.957497,L. Messi,105.0,RW,93,93,97.916667,97.916667,54.838710,...,False,0,1,0,0,0,1,0,0,1
2,190871,7.115582,Neymar,123.0,LW,92,94,100.000000,95.833333,70.967742,...,False,0,0,1,1,0,0,0,0,1
3,176580,6.878326,L. Suárez,97.0,ST,92,92,95.833333,95.833333,54.838710,...,False,0,0,1,1,0,0,0,0,1
4,167495,6.415097,M. Neuer,61.0,GK,92,92,95.833333,95.833333,51.612903,...,False,1,0,1,0,0,1,0,0,1

In [417]:
fifa_merged=pd.merge(fifa_transformed,fifa2_df,how='inner',on="Player_ID")

In [418]:
fifa_merged=fifa_merged.drop(columns=['ln_value', 'Name_y','Position_y','Value (M)','Overall_y','Potential_y','Club','LS','ST','RS','LW','LF','pot_grade','ovr_grade','age_grade','val_grade','scale_score','adjGrade_scale','div_scale','special','birth_date','height_cm','weight_kg','nationality','eur_value','eur_wage','eur_release_clause'])
fifa_merged=fifa_merged.drop(columns=[ '1_on_1_rush_trait','acrobatic_clearance_trait','argues_with_officials_trait','avoids_using_weaker_foot_trait','backs_into_player_trait','bicycle_kicks_trait','cautious_with_crosses_trait','chip_shot_trait','chipped_penalty_trait','comes_for_crosses_trait','corner_specialist_trait','diver_trait','dives_into_tackles_trait','diving_header_trait','driven_pass_trait','early_crosser_trait',"fan's_favourite_trait",'fancy_flicks_trait','finesse_shot_trait','flair_trait','flair_passes_trait','gk_flat_kick_trait','gk_long_throw_trait','gk_up_for_corners_trait','giant_throw_in_trait','inflexible_trait','injury_free_trait','injury_prone_trait','leadership_trait','long_passer_trait','long_shot_taker_trait','long_throw_in_trait','one_club_player_trait','outside_foot_shot_trait','playmaker_trait','power_free_kick_trait','power_header_trait','puncher_trait','rushes_out_of_goal_trait','saves_with_feet_trait','second_wind_trait','selfish_trait','skilled_dribbling_trait','stutter_penalty_trait','swerve_pass_trait','takes_finesse_free_kicks_trait','target_forward_trait','team_player_trait','technical_dribbler_trait','tries_to_beat_defensive_line_trait'])

In [419]:
player_info_df=fifa_merged[['Player_ID','Name_x','Nationality','Age','Weight','Height']]
player_info_df.head()
player_info_df.set_index('Player_ID',inplace=True)
player_info_df.head()

                      Name_x Nationality  Age  Weight Height
Player_ID
158023              L. Messi   Argentina   31  159lbs    5'7
20801      Cristiano Ronaldo    Portugal   33  183lbs    6'2
190871             Neymar Jr      Brazil   26  150lbs    5'9
193080                De Gea       Spain   27  168lbs    6'4
192985          K. De Bruyne     Belgium   27  154lbs   5'11

In [420]:
fifa_merged=fifa_merged.drop(columns=['poacher_speciality',
 'speedster_speciality',
 'aerial_threat_speciality',
 'dribbler_speciality',
 'playmaker_speciality',
 'engine_speciality',
 'distance_shooter_speciality',
 'crosser_speciality',
 'free_kick_specialist_speciality',
 'tackling_speciality',
 'tactician_speciality',
 'acrobat_speciality',
 'strength_speciality',
 'clinical_finisher_speciality',
 'prefers_rs',
 'prefers_rw',
 'prefers_rf',
 'prefers_ram',
 'prefers_rcm',
 'prefers_rm',
 'prefers_rdm',
 'prefers_rcb',
 'prefers_rb',
 'prefers_rwb',
 'prefers_st',
 'prefers_lw',
 'prefers_cf',
 'prefers_cam',
 'prefers_cm',
 'prefers_lm',
 'prefers_cdm',
 'prefers_cb',
 'prefers_lb',
 'prefers_lwb',
 'prefers_ls',
 'prefers_lf',
 'prefers_lam',
 'prefers_lcm',
 'prefers_ldm',
 'prefers_lcb',
 'prefers_gk',
 'foot_Left',
 'foot_Right',
 'att_rate_High',
 'att_rate_Low',
 'att_rate_Medium',
 'defend_rate_High',
 'defend_rate_Low',
 'defend_rate_Medium'])

In [421]:
fifa_merged.head()
fifa_merged.set_index('Player_ID',inplace=True)

In [422]:
attackers=fifa_merged.loc[(fifa_merged['Position_x']=='ST') | (fifa_merged['Position_x']=='RW') | (fifa_merged['Position_x']=='LW') | (fifa_merged['Position_x']=='CF')]

In [423]:
midfielders=fifa_merged.loc[(fifa_merged['Position_x']=='CDM') | (fifa_merged['Position_x']=='LM') | (fifa_merged['Position_x']=='RM') | (fifa_merged['Position_x']=='CAM')]

In [424]:
defenders=fifa_merged.loc[(fifa_merged['Position_x']=='CB') | (fifa_merged['Position_x']=='LB') | (fifa_merged['Position_x']=='RB')]

In [425]:
goalkeepers=fifa_merged.loc[(fifa_merged['Position_x']=='GK')]

In [426]:
league=fifa_merged[['league','league_id']]
league.drop_duplicates('league_id',inplace=True)
league=league.sort_values('league').head()
league.set_index('league_id',inplace=True)
league.head()

C:\conda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                             league
league_id
0                                 0
1             Argentinian Superliga
2               Australian A-League
3               Austrian Bundesliga
4          Belgian First Division A

In [427]:
clubs=fifa_merged[['club','club_id']]
clubs.drop_duplicates('club_id',inplace=True)
clubs.sort_values('club').head()
clubs.set_index('club_id',inplace=True)

C:\conda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [428]:
attackers=attackers.drop(columns=['Jersey Number',
 'Height',
 'Weight',
 'grade',
 'full_name',
 'club',
 'club_id',
 'age',
 'league',
 'league_id',
 'Age',
 'Nationality',
 'Overall_x',
 'Potential_x',
 'Value',
 'Wage',
 'Preferred Foot',
 'International Reputation',
 'Weak Foot',
 'Skill Moves',
 'Work Rate',
 'Body Type'])

In [429]:
attackers = attackers.rename(columns={"Name_x": "Name",
                                                         "Position_x": "Position",})
attackers.head()

,Name,Position,pac,sho,pas,dri,defend,phy,international_reputation,skill_moves,...,cb,lb,lwb,ls,lf,lam,lcm,ldm,lcb,gk
Player_ID,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,ST,90,93,82,90,33,80,5,5,...,53,61,66,92,91,89,82,62,53,0
190871,Neymar Jr,LW,92,84,79,95,30,60,5,5,...,46,59,64,84,88,88,79,59,46,0
188545,R. Lewandowski,ST,81,88,75,86,38,82,4,3,...,57,58,61,88,87,84,78,62,57,0
202126,H. Kane,ST,73,87,72,78,42,83,3,3,...,57,60,62,84,82,79,74,62,57,0
153079,S. Agüero,ST,87,88,75,89,23,72,4,4,...,44,52,57,86,87,85,75,54,44,0

In [430]:
defenders=defenders.drop(columns=['Jersey Number',
 'Height',
 'Weight',
 'grade',
 'full_name',
 'club',
 'club_id',
 'age',
 'league',
 'league_id',
 'Age',
 'Nationality',
 'Overall_x',
 'Potential_x',
 'Value',
 'Wage',
 'Preferred Foot',
 'International Reputation',
 'Weak Foot',
 'Skill Moves',
 'Work Rate',
 'Body Type'])

In [431]:
defenders = defenders.rename(columns={"Name_x": "Name",
                                                         "Position_x": "Position",})
defenders.head()

,Name,Position,pac,sho,pas,dri,defend,phy,international_reputation,skill_moves,...,cb,lb,lwb,ls,lf,lam,lcm,ldm,lcb,gk
Player_ID,,,,,,,,,,,,,,,,,,,,,
182493,D. Godín,CB,67,48,65,63,88,79,3,2,...,86,79,76,64,62,63,69,80,86,0
176676,Marcelo,LB,78,69,80,86,83,79,4,4,...,82,84,85,77,80,80,81,83,82,0
205600,S. Umtiti,CB,74,64,71,71,82,79,3,2,...,81,79,78,69,69,69,73,79,81,0
189332,Jordi Alba,LB,93,69,75,82,81,72,3,3,...,78,83,84,75,78,78,78,80,78,0
191043,Alex Sandro,LB,86,65,77,81,81,84,3,3,...,81,84,84,75,76,77,78,81,81,0

In [432]:
midfielders=midfielders.drop(columns=['Jersey Number',
 'Height',
 'Weight',
 'grade',
 'full_name',
 'club',
 'club_id',
 'age',
 'league',
 'league_id',
 'Age',
 'Nationality',
 'Overall_x',
 'Potential_x',
 'Value',
 'Wage',
 'Preferred Foot',
 'International Reputation',
 'Weak Foot',
 'Skill Moves',
 'Work Rate',
 'Body Type'])

In [433]:
midfielders = midfielders.rename(columns={"Name_x": "Name",
                                                         "Position_x": "Position",})
midfielders.head()

,Name,Position,pac,sho,pas,dri,defend,phy,international_reputation,skill_moves,...,cb,lb,lwb,ls,lf,lam,lcm,ldm,lcb,gk
Player_ID,,,,,,,,,,,,,,,,,,,,,
194765,A. Griezmann,CAM,86,85,78,87,30,68,4,4,...,48,56,60,85,85,84,76,57,48,0
189511,Sergio Busquets,CDM,40,59,79,74,82,81,4,3,...,80,76,77,68,72,75,81,83,80,0
231747,K. Mbappé,RM,90,80,74,85,47,74,3,4,...,58,64,67,82,82,81,75,64,58,0
209331,M. Salah,RM,93,73,74,87,45,66,3,4,...,56,64,68,78,82,81,75,64,56,0
200145,Casemiro,CDM,62,68,74,72,84,86,3,2,...,83,78,77,72,72,74,79,84,83,0

In [434]:
goalkeepers=goalkeepers.drop(columns=['Jersey Number',
 'Height',
 'Weight',
 'grade',
 'full_name',
 'club',
 'club_id',
 'age',
 'league',
 'league_id',
 'Age',
 'Nationality',
 'Overall_x',
 'Potential_x',
 'Value',
 'Wage',
 'Preferred Foot',
 'International Reputation',
 'Weak Foot',
 'Skill Moves',
 'Work Rate',
 'Body Type'])

In [435]:
goalkeepers = goalkeepers.rename(columns={"Name_x": "Name",
                                                         "Position_x": "Position",})
goalkeepers.set_index('Player_ID', inplace= True)

KeyError: 'Player_ID'

In [436]:
list(goalkeepers.columns.values.tolist())

['Name',
 'Position',
 'pac',
 'sho',
 'pas',
 'dri',
 'defend',
 'phy',
 'international_reputation',
 'skill_moves',
 'weak_foot',
 'crossing',
 'finishing',
 'heading_accuracy',
 'short_passing',
 'volleys',
 'dribbling',
 'curve',
 'free_kick_accuracy',
 'long_passing',
 'ball_control',
 'acceleration',
 'sprint_speed',
 'agility',
 'reactions',
 'balance',
 'shot_power',
 'jumping',
 'stamina',
 'strength',
 'long_shots',
 'aggression',
 'interceptions',
 'positioning',
 'vision',
 'penalties',
 'composure',
 'marking',
 'standing_tackle',
 'sliding_tackle',
 'gk_diving',
 'gk_handling',
 'gk_kicking',
 'gk_positioning',
 'gk_reflexes',
 'rs',
 'rw',
 'rf',
 'ram',
 'rcm',
 'rm',
 'rdm',
 'rcb',
 'rb',
 'rwb',
 'st',
 'lw',
 'cf',
 'cam',
 'cm',
 'lm',
 'cdm',
 'cb',
 'lb',
 'lwb',
 'ls',
 'lf',
 'lam',
 'lcm',
 'ldm',
 'lcb',
 'gk']

In [437]:
rds_connection_string = "root:up#XkMu5v1oz@127.0.0.1:3306/fifa"
engine = create_engine(f'mysql+pymysql://{rds_connection_string}')

In [444]:
engine.table_names()

['attackers',
 'club',
 'clubs',
 'defenders',
 'forwards',
 'goalkeepers',
 'league',
 'leagues',
 'midfielders',
 'player',
 'player_info']

In [439]:
league.to_sql(name='leagues', con=engine, if_exists='replace',index_label='league_id',index=True)

In [457]:
clubs['club']=clubs['club'].astype('str')
# df['Volume'] = df['Volume'].astype('str')
# df['Volume'] = df['Volume'].str.replace(',', '')
clubs.columns

C:\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

Index(['club'], dtype='object')

In [443]:
goalkeepers

,Name,Position,pac,sho,pas,dri,defend,phy,international_reputation,skill_moves,...,cb,lb,lwb,ls,lf,lam,lcm,ldm,lcb,gk
Player_ID,,,,,,,,,,,,,,,,,,,,,
193080,De Gea,GK,90,85,87,90,58,86,4,1,...,0,0,0,0,0,0,0,0,0,90
200389,J. Oblak,GK,84,90,77,84,52,87,3,1,...,0,0,0,0,0,0,0,0,0,88
192448,M. ter Stegen,GK,84,83,87,86,45,81,3,1,...,0,0,0,0,0,0,0,0,0,85
192119,T. Courtois,GK,85,91,69,88,49,86,4,1,...,0,0,0,0,0,0,0,0,0,89
167495,M. Neuer,GK,91,90,95,89,60,91,5,1,...,0,0,0,0,0,0,0,0,0,92
167948,H. Lloris,GK,88,86,68,90,64,82,4,1,...,0,0,0,0,0,0,0,0,0,88
162835,S. Handanovič,GK,87,86,69,87,56,87,3,1,...,0,0,0,0,0,0,0,0,0,87
1179,G. Buffon,GK,89,88,74,84,46,90,4,1,...,0,0,0,0,0,0,0,0,0,89
193041,K. Navas,GK,89,78,72,88,53,80,3,1,...,0,0,0,0,0,0,0,0,0,85
210257,Ederson,GK,81,76,82,87,63,78,2,1,...,0,0,0,0,0,0,0,0,0,83
212831,Alisson,GK,75,76,70,86,39,78,1,1,...,0,0,0,0,0,0,0,0,0,80
186153,W. Szczęsny,GK,83,77,74,87,49,78,3,1,...,0,0,0,0,0,0,0,0,0,82
199482,A. Lopes,GK,86,79,73,85,62,79,2,1,...,0,0,0,0,0,0,0,0,0,83
198009,M. Perin,GK,80,85,71,90,56,78,2,1,...,0,0,0,0,0,0,0,0,0,83
192563,B. Leno,GK,85,84,74,83,49,85,3,1,...,0,0,0,0,0,0,0,0,0,85
190941,L. Hrádecký,GK,79,77,73,85,41,79,2,1,...,0,0,0,0,0,0,0,0,0,81
178750,Sergio Asenjo,GK,86,83,76,85,56,82,2,1,...,0,0,0,0,0,0,0,0,0,84
167628,S. Ruffier,GK,82,84,77,87,48,85,3,1,...,0,0,0,0,0,0,0,0,0,85
163587,K. Schmeichel,GK,83,82,82,86,61,80,2,1,...,0,0,0,0,0,0,0,0,0,83
206585,Kepa,GK,78,81,75,83,33,76,1,1,...,0,0,0,0,0,0,0,0,0,80
204935,J. Pickford,GK,77,76,85,82,44,73,1,1,...,0,0,0,0,0,0,0,0,0,77
200316,T. Horn,GK,83,81,83,86,48,82,2,1,...,0,0,0,0,0,0,0,0,0,84
194404,Neto,GK,84,80,74,83,51,74,2,1,...,0,0,0,0,0,0,0,0,0,80
193698,O. Baumann,GK,82,82,64,84,49,81,2,1,...,0,0,0,0,0,0,0,0,0,82
192593,D. Subašić,GK,84,79,79,87,53,85,3,1,...,0,0,0,0,0,0,0,0,0,85
179783,R. Fährmann,GK,83,86,52,87,43,85,2,1,...,0,0,0,0,0,0,0,0,0,84
178086,Adán,GK,80,83,72,82,55,81,2,1,...,0,0,0,0,0,0,0,0,0,81
178005,Rui Patrício,GK,85,81,80,82,55,79,3,1,...,0,0,0,0,0,0,0,0,0,83
177683,Y. Sommer,GK,81,82,83,83,51,80,3,1,...,0,0,0,0,0,0,0,0,0,83
163705,S. Mandanda,GK,86,78,75,83,48,77,3,1,...,0,0,0,0,0,0,0,0,0,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227545,T. Ryan,GK,55,49,45,59,46,51,1,1,...,0,0,0,0,0,0,0,0,0,54
240346,S. George,GK,56,52,48,55,30,53,1,1,...,0,0,0,0,0,0,0,0,0,54
228369,J. Walton,GK,52,47,46,49,46,46,1,1,...,0,0,0,0,0,0,0,0,0,50
231722,A. Long,GK,57,58,48,51,20,48,1,1,...,0,0,0,0,0,0,0,0,0,53
230971,N. Tzanev,GK,55,48,47,53,48,49,1,1,...,0,0,0,0,0,0,0,0,0,53
237167,R. Miura,GK,58,54,52,48,24,49,1,1,...,0,0,0,0,0,0,0,0,0,53
227975,H. Fossdal,GK,54,48,45,56,44,49,1,1,...,0,0,0,0,0,0,0,0,0,53
235912,K. Al Mozaibri,GK,61,50,56,53,26,49,1,1,...,0,0,0,0,0,0,0,0,0,53
236431,E. Alarcón,GK,56,55,55,49,26,44,1,1,...,0,0,0,0,0,0,0,0,0,51
239811,Lee Yunoh,GK,54,52,55,59,19,52,1,1,...,0,0,0,0,0,0,0,0,0,53
216262,M. Urwin,GK,55,45,51,58,48,53,1,1,...,0,0,0,0,0,0,0,0,0,53
237269,J. McGuire,GK,49,52,69,54,34,51,1,1,...,0,0,0,0,0,0,0,0,0,53
240386,G. Nyberg,GK,55,49,53,56,20,53,1,1,...,0,0,0,0,0,0,0,0,0,52
238907,H. Abdulmajeed,GK,60,52,45,55,19,44,1,1,...,0,0,0,0,0,0,0,0,0,52
240218,A. Weidinger,GK,51,54,56,49,23,56,1,1,...,0,0,0,0,0,0,0,0,0,52
240531,M. Al Baqawi,GK,52,49,49,54,28,40,1,1,...,0,0,0,0,0,0,0,0,0,49
239019,J. Delianov,GK,52,54,55,51,26,50,1,1,...,0,0,0,0,0,0,0,0,0,51
240565,G. Meli,GK,52,54,55,56,30,49,1,1,...,0,0,0,0,0,0,0,0,0,52
227770,M. Boney,GK,54,47,44,55,43,49,1,1,...,0,0,0,0,0,0,0,0,0,52
232676,N. Hatta,GK,54,48,45,54,28,52,1,1,...,0,0,0,0,0,0,0,0,0,52
240884,A. André Jr,GK,46,52,65,54,51,50,1,1,...,0,0,0,0,0,0,0,0,0,52
232126,D. Craddock,GK,52,57,51,47,22,47,1,1,...,0,0,0,0,0,0,0,0,0,51
237917,A. Suzuki,GK,49,51,58,58,29,52,1,1,...,0,0,0,0,0,0,0,0,0,52
241018,F. Nørgaard,GK,52,50,54,57,27,43,1,1,...,0,0,0,0,0,0,0,0,0,50
240286,J. García,GK,47,56,54,52,22,44,1,1,...,0,0,0,0,0,0,0,0,0,50
240339,J. Granlund,GK,49,53,49,53,23,43,1,1,...,0,0,0,0,0,0,0,0,0,50
237045,R. Pasquel,GK,54,53,47,56,21,40,1,1,...,0,0,0,0,0,0,0,0,0,50
237463,A. Kelsey,GK,46,47,49,48,28,42,1,1,...,0,0,0,0,0,0,0,0,0,46
233398,W. Henry,GK,56,46,45,54,22,38,1,1,...,0,0,0,0,0,0,0,0,0,49
221669,M. Hurst,GK,45,49,50,45,41,50,1,1,...,0,0,0,0,0,0,0,0,0,48